# Generated by Django 5.1.4 on 2025-01-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_repo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
