# Generated by Django 5.1.4 on 2025-01-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_repo_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='repo',
            name='content',
        ),
    ]
